# Generated by Django 2.2.1 on 2019-05-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masjidaidsapp', '0002_auto_20190515_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masjidsimages',
            name='masjid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masjid_uploaded_mages', to='masjidaidsapp.Masjid'),
        ),
    ]
